import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<<<<<<< HEAD
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

=======
export const metadata = {
  title: "CSN",
  description: "CSN HUB – Onchain miniapps built by Coinisan",
  icons: {
    icon: "/favicon.png", // veya .ico dosyan varsa "/favicon.ico"
  },
};


>>>>>>> 5c27dd80baac6258299889cf6d7ba725173624d9
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
